packages:
  - packages/*
  - apps/*
  - internal
  - examples

catalog:
  react: ^19.2.3
  react-dom: ^19.2.3
  typescript: ~5.9.3
  esbuild: ^0.27.0
  lightningcss: ^1.30.1
  "@mui/material": ^7.3.5
  "@mui/utils": ^7.3.5
  "@playwright/test": ~1.56.1
  "@types/node": ^22.19.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3

overrides:
  lightningcss: 1.30.1 # https://github.com/parcel-bundler/lightningcss/issues/1065

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@stratakit/*"
  - "@itwin/*"
  - react
  - react-dom

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
