packages:
  - packages/*
  - apps/*
  - internal
  - examples

catalog:
  "@mui/material": ^7.3.5
  "@mui/utils": ^7.3.5
  "@playwright/test": ~1.58.1
  "@types/node": ^22.19.1
  "@types/react": ^19.2.10
  "@types/react-dom": ^19.2.3
  esbuild: ^0.27.2
  lightningcss: ^1.31.1
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: ~5.9.3

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@stratakit/*"
  - "@itwin/*"
  - react
  - react-dom

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp

overrides:
  lightningcss: 1.30.1

patchedDependencies:
  "@astrojs/starlight": patches/@astrojs__starlight.patch
