packages:
  - packages/*
  - apps/*
  - internal
  - examples

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ~5.8.3
  esbuild: ^0.25.5
  lightningcss: ^1.30.1
  "@playwright/test": ~1.52.0
  "@types/node": ^22.15.29
  "@types/react": ^19.1.5
  "@types/react-dom": ^19.1.5
