packages:
  - packages/*
  - apps/*
  - internal
  - examples

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ~5.9.3
  esbuild: ^0.25.11
  lightningcss: ^1.30.1
  "@playwright/test": ~1.56.1
  "@types/node": ^22.18.11
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@stratakit/*"
  - "@itwin/*"
