packages:
  - packages/*
  - apps/*
  - internal

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ~5.8.2
  esbuild: ^0.25.1
  lightningcss: ^1.29.2
  "@types/node": ^22.13.10
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
