packages:
  - packages/*
  - apps/*
  - internal

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ~5.8.3
  esbuild: ^0.25.3
  lightningcss: ^1.29.3
  "@playwright/test": ~1.52.0
  "@types/node": ^22.14.1
  "@types/react": ^19.1.2
  "@types/react-dom": ^19.1.2
