packages:
  - packages/*
  - apps/*
  - internal
  - examples

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ~5.8.3
  esbuild: ^0.25.5
  lightningcss: ^1.30.1
  "@playwright/test": ~1.53.0
  "@types/node": ^22.15.32
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
