packages:
  - packages/*
  - apps/*
  - internal
  - examples

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ~5.9.3
  esbuild: ^0.25.10
  lightningcss: ^1.30.2
  "@playwright/test": ~1.55.0
  "@types/node": ^22.18.8
  "@types/react": ^19.2.0
  "@types/react-dom": ^19.2.0

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@stratakit/*"
  - "@itwin/*"
