packages:
  - packages/*
  - apps/*
  - internal
  - examples

catalog:
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ~5.9.2
  esbuild: ^0.25.9
  lightningcss: ^1.30.1
  "@playwright/test": ~1.55.0
  "@types/node": ^22.18.1
  "@types/react": ^19.1.12
  "@types/react-dom": ^19.1.9
