packages:
  - packages/*
  - apps/*
  - internal
  - examples

catalog:
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ~5.9.2
  esbuild: ^0.25.8
  lightningcss: ^1.30.1
  "@playwright/test": ~1.54.2
  "@types/node": ^22.17.0
  "@types/react": ^19.1.9
  "@types/react-dom": ^19.1.7
