/*---------------------------------------------------------------------------------------------
 * Copyright (c) Bentley Systems, Incorporated. All rights reserved.
 * See LICENSE.md in the project root for license terms and full copyright notice.
 *--------------------------------------------------------------------------------------------*/
export const components = {
	foundations: ["Root", "Icon"],
	bricks: [
		"Anchor",
		"Avatar",
		"Badge",
		"Button",
		"Checkbox",
		"Divider",
		"Field",
		"IconButton",
		"Kbd",
		"ProgressBar",
		"Radio",
		"Select",
		"Skeleton",
		"Spinner",
		"Switch",
		"Text",
		"TextBox",
		"Tooltip",
	],
	structures: [
		"AccordionItem",
		"Banner",
		"Chip",
		"DropdownMenu",
		"ErrorRegion",
		"List",
		"Table",
		"Tabs",
		"Toolbar",
		"Tree",
	],
	compat: [
		"Anchor",
		"Avatar",
		"Badge",
		"Button",
		"Checkbox",
		"Divider",
		"DropdownButton",
		"DropdownMenu",
		"Icon",
		"Input",
		"InputGrid",
		"Kbd",
		"Label",
		"LabeledInput",
		"LabeledTextarea",
		"ProgressLinear",
		"ProgressRadial",
		"Radio",
		"StatusMessage",
		"Tabs",
		"Tag",
		"Text",
		"Textarea",
		"Tooltip",
		"VisuallyHidden",
	],
};
